-- create tables

create table sm_posts (
    id              number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
                    constraint sm_posts_id_pk primary key,
    post_comment    varchar2(4000 char),
    file_blob       blob,
    file_mime       varchar2(255 char),
    file_name       varchar2(255 char),
    lat             number,
    lon             number,
    created         date not null,
    created_by      varchar2(255 char) not null,
    updated         date not null,
    updated_by      varchar2(255 char) not null
);


create table sm_reactions (
    id            number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
                  constraint sm_reactions_id_pk primary key,
    post_id       number                  constraint sm_reactions_post_id_fk
                  references sm_posts,
    reaction      varchar2(16 char),
    lat           number,
    lon           number,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);

-- table index
create index sm_reactions_i1 on sm_reactions (post_id);



-- triggers
create or replace trigger sm_posts_biu
    before insert or update
    on sm_posts
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end sm_posts_biu;
/


create or replace trigger sm_reactions_biu
    before insert or update
    on sm_reactions
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end sm_reactions_biu;
/


-- Generated by Quick SQL 1.2.9 9/25/2026, 12:08:42 PM

/*




posts /auditcols
    post_comment vc4000
    file_blob blob
    file_mime vc255
    file_name vc255
    lat num
    lon num
    reactions /auditcols
        post_id /fk posts
        reaction vc16
        lat num
        lon num

 Non-default options:
# settings = {"apex":true,"prefix":"sm"}

*/